WCMumbai/WordCamp.org

wcm17.css

CSS refactoring for better readability

refactoring for better readability

---

wcm17.css

- unwanted & redundant properties removed
- images loaded securely via https

CSS cleanup

---

wcm17.css

This css changes will make organizers pages look like the below images
Feel free to ignore this if you feel current one looks better :)

Organizers layout

---

wcm17.css

Block layout improvised and icon font switched from dashicons to fontawesome. Check screenshot
Will further look into improving the layout.

Attendees layout

---

wcm17.css

Localhost fix

---

wcm17.css

We will have something like this:

Sponsors widget layout

---

wcm17.css

Page title & footer check the screenshot for references:
Title
Footer

Page title footer

---

wcm17.css

Attendees tweaks

---

wcm17.css

tickets minor formatting, look into further improving it

Tickets tweaks

---

wcm17.css

tickets CSS moved before mobile code so that it does not override mobile formatting previously added.

Tickets rules position

---

wcm17.css

Page title size

---

wcm17.css

Sponsor logo hover shadow/border fix

---

wcm17.css

We will have something like this

Discounts layout

---

wcm18.css

Fix CSS for Mobile view and Code Formatted

Code formatted and fix css

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Add Githu Issues and PR templates

Add github pr and isses create templetes

---

wcm18.css

SUbmenu Item

---

wcm18.css

sample comment

---

wcm18.css

Design added from line no 536 - 543

Dropdown menu design fixed

---

wcm18.css

Horizontal scroll bar coming in Firefox and Opera - Fixed
Desktop Menus - Fixed
Mobile - Left and Right Padding needed for pages. - Fixed 
Mobile - Left and Right Padding needed for Post Navigation and Comment section - Fixed

Desktop Menu & Mobile Padding

---

wcm18.css

This style removed.
header{
overflow:hidden !important;
}

Desktop Sub Menu  not visible

---

wcm18.css

Code Removed
/* Deskptop Menus Design Fixed*/
.page-navigation-container ul ul{
top: 2.4em;
}

Sub Menu Top Position Fixed

---

wcm18.css

Desktop menu modifications
